# CALCUL DU PROFIT DE L'ENTREPRISE

### PROFIT

In [6]:
ordinateurs_stock = 1000
ordinateurs_vendus = 650
ordinateur_prix = 800

In [10]:
print(ordinateurs_stock)
print("ordinateur stock:", ordinateurs_stock, "fin du print")

1000
ordinateur stock: 1000 fin du print

In [11]:
# profit realise sur les ordinateurs vendus
profit = ordinateurs_vendus * ordinateur_prix
print("Le profit realise est de:", profit)

Le profit realise est de: 520000

In [12]:
stock_restant = ordinateurs_stock - ordinateurs_vendus
print("stock_restant:", stock_restant)

stock_restant: 350

#### Variables et data types

In [ ]:
# lettre (String) et chiffres
name = "Firat"
Age = 30

# Boolean value: True or False 
is_present = True
is_summer = False 
    ## type de cas d'utilisation: est ce qu'on est en ete? Checker la date
if date.today().month in [6, 7, 8]:
    is_summer = True
else: 
    is_summer = False

In [ ]:
# operations sur entiers numeriques: + * - /
Age*30

900

In [19]:
150+30

180

In [20]:
name + " Erman"

'Firat Erman'

In [17]:
name*3

'FiratFiratFirat'

In [21]:
name

'Firat'

In [22]:
"firat" + "erman"

'firaterman'

#### Operators

In [ ]:
# +, -, *, /, //, % , **

print(5 + 3)
print(5 - 3)
print(5 * 3)
print(5 / 3)   # division float
print(10 // 3)  # division entier
print(10 % 3)   # modulo : nominateur du modulo - division entier sur les memes nominateurs denominateurs
print(5 ** 3)  # puissance

8
2
15
1.6666666666666667
3
1
125

In [26]:
print(10 % 3)

1

##### Operateurs: egal, plus grand, plus petit, different etc...

In [ ]:
# generalement utilise dans les conditions if pour verifier certains criteres
age_legal_pour_boire = 18
pierre_age = 20
Marie_age = 16

if pierre_age >= age_legal_pour_boire:
    print("Pierre peut boire de l'alcool car il est majeur")
else:
    print("Pierre ne peut pas boire de l'alcool car il est mineur")

In [ ]:
if pierre_age != Marie_age:
    print("Pierre et Marie n'ont pas le meme age")
if pierre_age == Marie_age:
    print("Pierre et Marie ont le meme age")
if pierre_age > Marie_age:
    print("Pierre est plus age que Marie")
if Marie_age < age_legal_pour_boire:
    print("Marie est mineure")

In [34]:
# conditions : 
# if, else 
# if, elif, elif, else

#### Data Structures

In [11]:
#3 types de data structures: LIST, SETS, TUPLES 
#   - LIST : mutable (ajouter et supprimer des elements de la liste), peut avoir des doublons 
#   - SET: NO mutable, NO doublons (on a des valeurs unique)
#   - TUPLES : NO mutable, OK doublons 
eleves_paris = ["Marie", "Marie", "Jean", "Luc", "Sophie", "Sophie"] # LIST 


colors = {"red", "blue", "green"} #SET 
# exemple: si je veux avoir les eleves unique de paris, sans doublons et sans possibilite de changer plus tard
# je peux convertir une list en set 
eleves_paris_unique = set(eleves_paris)
print(eleves_paris_unique)

eleves = ("Marie", "Jean") # TUPLES

{'Sophie', 'Marie', 'Luc', 'Jean'}

In [6]:
# Dictionnaires: key-value pairs

exemple_de_dictionnaire = {
    "key": "value",
    "key": "value",
    "key": "value",
    "key": "value",
}

# key toujours entre guillemets ""
# value peut etre string, integer, boolean, list, set, tuple, dictionnaire etc
profile_user_dict = {
    "name": "DeGaulle",
    "surname": "Mandela",
    "age": 25,
    "is_student": True,
    "loisirs": ["football", "cinema", "voyage"]
}

# type de besoin d'un dictionnaire: mapping employe location avec des bureaux specifiques
employee_bureau_dict = {
    "bureau_paris": ["Alice", "Bob", "Charlie"],
    "bureau_lyon": ["David", "Eva"],
    "bureau_marseille": ["Frank", "Grace", "Hannah"],
    "bureau_new_york": ["Ivy", "Jack"]
}

for bureau, employees in employee_bureau_dict.items():
    print("Bureau:", bureau)
    print("Employees:", employees)
    print("-----")

Bureau: bureau_paris
Employees: ['Alice', 'Bob', 'Charlie']
-----
Bureau: bureau_lyon
Employees: ['David', 'Eva']
-----
Bureau: bureau_marseille
Employees: ['Frank', 'Grace', 'Hannah']
-----
Bureau: bureau_new_york
Employees: ['Ivy', 'Jack']
-----

In [6]:
name = "Pierre"

# dans une liste, chaque element est separe par une virgule
eleves_paris = ["Marie", "Jean", "Luc", "Sophie"]
eleves_bordeaux = ["Alice", "Paul", "Emma", "Lucas"]

# concatener deux listes/additioner deux listes entre elles
total_eleves = eleves_paris + eleves_bordeaux
print("Liste totale des eleves:", total_eleves)

Liste totale des eleves: ['Marie', 'Jean', 'Luc', 'Sophie', 'Alice', 'Paul', 'Emma', 'Lucas']

In [7]:
# pour ajouter un element a une liste: append 
eleves_paris.append("Julien")
print(eleves_paris)

['Marie', 'Jean', 'Luc', 'Sophie', 'Julien']

### FOR LOOP

In [ ]:
# simple for loop pour iterer dans la liste des eleves de paris et print chaque eleve un par un 
for personne in eleves_paris:
    print(personne)

In [7]:
#### FOR LOOP: itere a travers une liste pour appliquer un critere (operators, classification, peu importe)
liste_de_pays_a_voyager_2026 = ["Bresil", "Espagne", "Inde", "Senegal"]

continent_amerique = ["Bresil", "USA", "Mexique"]
continent_europe = ["Espagne", "portugal", "France", "italie"]
continent_afrique = ["mali", "Cote d'ivoir", "Senegal", "egypt","Congo"]
continent_asie = ["Inde", "chine", "coree du sud"]

# Dans quelles continent je vais voyager en 2026?
continent_visite = []

for pays in liste_de_pays_a_voyager_2026:
    if pays in continent_amerique:
        continent_visite.append("amerique")
    elif pays in continent_europe:
        continent_visite.append("europe")
    elif pays in continent_afrique:
        continent_visite.append("afrique")
    elif pays in continent_asie:
        continent_visite.append("asie")

In [8]:
print(continent_visite)

['amerique', 'europe', 'asie', 'afrique']

In [ ]:
# simple for loop pour iterer dans la liste des eleves de paris et print chaque eleve un par un 
for personne in eleves_paris:
    print(personne)

In [ ]:
John_adresse = "bordeaux" # un seul egal car on definit une variable
# ajouter le prenom "john" dans la liste qui correspond a sa location : soit eleves_paris soit eleves_bordeaux
if John_adresse == "paris": # il y a deux egales car c'est un operateur 
    eleves_paris.append("John")
elif John_adresse == "bordeaux":
    eleves_bordeaux.append("John")

print(eleves_bordeaux)

['Alice', 'Paul', 'Emma', 'Lucas', 'John']

### FUNCTIONS

In [ ]:
### une fonction permet d'automatiser une tache. On donne un nom a une fonction, et on peut faire appel
### a la fonction lorsqu'on veut, en lui fournissant a chaque fois des inputs.

In [1]:
# Calculer la moyenne general d'un seul etudiant 

# sans une fonction
note_de_math = 15
note_de_francais = 12
note_de_machine_learning = 14

somme_des_notes = note_de_math + note_de_francais + note_de_machine_learning
nombre_de_matieres = 3

moyenne_generale = somme_des_notes / nombre_de_matieres

print("La moyenne generale de l'etudiant est de:", moyenne_generale)

La moyenne generale de l'etudiant est de: 13.666666666666666

In [10]:
# avec une fonction 

def calculer_moyenne_eleve(note1, note2, note3, nb_de_matieres):
    somme_des_notes = note1 + note2 + note3
    moyenne_generale = somme_des_notes / nb_de_matieres

    return moyenne_generale

In [13]:
note_de_math_fanny = 18
note_de_francais_fanny = 17
note_de_machine_learning_fanny = 19

# Je vais fair appel a ma fonction creer pour cette tache
# obligation de mettre les memes nombre d'elements en inputs, ici 4 elements ont ete definis dans la fonction
#  
moyenne_de_fanny = calculer_moyenne_eleve(note_de_math_fanny, note_de_francais_fanny, note_de_machine_learning_fanny, 3)
print(moyenne_de_fanny)

18.0

In [18]:
def concatener_prenom_nom(prenom, nom):
    nom_complet = prenom + "_" + nom
    print("prenom:", prenom)
    print("nom", nom)
    print("nom complet:", nom_complet)
    return nom_complet

In [19]:
concatener_prenom_nom("Jean", "Dupont")

prenom: Jean
nom Dupont
nom complet: Jean_Dupont

'Jean_Dupont'

In [27]:

def nettoyer_text(input_text):
    caracteres_a_supprimer = ["#", "$", "%", "!',", "@", "?!)*()", "*", "&"]
    texte_nettoye = input_text

    for caractere in caracteres_a_supprimer:
        texte_nettoye = texte_nettoye.replace(caractere, "")

    return texte_nettoye

In [28]:
email_recu_par_john = "Hello, % I am here today#$!', how are you?@@@ What are you doing?!)*()"
nettoyer_text(email_recu_par_john)

'Hello,  I am here today how are you? What are you doing'

In [30]:
nettoyer_text("*%*%*%* le nouveau site de google est en ligne et ut$%$ilise d*s nouve@u%x modeles A*&&%I")

' le nouveau site de google est en ligne et utilise ds nouveux modeles AI'

## LIBRARIES

In [ ]:
# les librairies sur python on peut les importer, et elles nous permettent d'appliquer des fonctions deja predefinies
# dans le package


# step 1: il faut d'abord telecharger/installer la libraire 
# step 2: importer la librairie dans le code  
# note: une fois telecharger, plus besoin de le retelecharger, il faut juste faire l'import cad la step2


# step1: pour telercharger/installer : pip3 install nom_de_la_librarie 
# 2 moyens de le faire soit sur terminal soit directment dans le script/notebook python:
    # solution1 via terminal: pip3 install numpy
    # solution2 via script/notebook: !pip3 install numpy

In [1]:
# installation des packages, soit pip soit pip3 (pip3 pour python3) mais generalement c'est pip3
!pip3 install pandas

Requirement already satisfied: pandas in /Users/firaterman/Documents/bidabi_2026/venv/lib/python3.14/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in /Users/firaterman/Documents/bidabi_2026/venv/lib/python3.14/site-packages (from pandas) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/firaterman/Documents/bidabi_2026/venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/firaterman/Documents/bidabi_2026/venv/lib/python3.14/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/firaterman/Documents/bidabi_2026/venv/lib/python3.14/site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /Users/firaterman/Documents/bidabi_2026/venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
# maintenant que ca a ete telechargfer, je l'ai dans mon disque dur, donc je peux l'importer import pandas 
import pandas as pd

In [ ]:
# Dataframe: c'est une table au format tabulaire lignes et colonnes
# on donne un dictionnaire a pandas pour creer la dataframe 
list_eleve_df = pd.DataFrame({
    "prenoms": ["Marie", "Jean", "Luc", "Sophie"],
    "noms": ["Dupont", "Martin", "Bernard", "Durand"],
    "ages": [20, 22, 19, 21],
    "ville": ["Paris", "Bordeaux", "Lyon", "Marseille"],
    "code postal": [75001, 33000, 69000, 13000],
    "pays": ["France", "France", "France", "France"],
    "loisirs": ["lecture", "sport", "musique", "cinema"]
})

In [5]:
list_eleve_df

  prenoms     noms  ages      ville  code postal    pays  loisirs
0   Marie   Dupont    20      Paris        75001  France  lecture
1    Jean   Martin    22   Bordeaux        33000  France    sport
2     Luc  Bernard    19       Lyon        69000  France  musique
3  Sophie   Durand    21  Marseille        13000  France   cinema

In [56]:
# import d'un fichier csv dans une dataframe pandas 
product_df = pd.read_csv("data/products.csv")
product_df

            product   price  quantity  weight  height location_available
0        Macbook_M1  899.99        15    2.30     1.8           New York
1  samsung_watch_x1  699.50        40    0.18     0.7         California
2    Tablet_applexo  399.00        25    0.50     0.6              Texas
3          Sony_m90  129.99        60    0.25     0.3            Florida
4  samsung_watch_x1  249.75        30    0.09     0.4         Washington
5         Monitorx1  299.99        20    4.50    15.2           Illinois
6      Keyboardx901   79.95        50    0.80     1.5               Ohio
7          Mousex12   39.99        70    0.12     0.9            Arizona
8      Printeras10c  189.00        10    6.80    12.4            Georgia
9      Webcamasdasd   59.49        45    0.20     1.2             Oregon

In [40]:
# type de colonnes dans la dataframe
product_df.dtypes

product                object
price                 float64
quantity                int64
weight                float64
height                float64
location_available     object
dtype: object

In [11]:
product_df.describe()

            price   quantity     weight     height
count   10.000000  10.000000  10.000000  10.000000
mean   304.665000  36.500000   1.574000   3.500000
std    288.057354  19.867617   2.310667   5.488776
min     39.990000  10.000000   0.090000   0.300000
25%     92.460000  21.250000   0.185000   0.625000
50%    219.375000  35.000000   0.375000   1.050000
75%    374.247500  48.750000   1.925000   1.725000
max    899.990000  70.000000   6.800000  15.200000

In [15]:
# python compte les valeurs en commencant par l'index 0: liste, dataframe etc..

#example list: je veux la premiere valeur de  la liste
continent_amerique = ["Bresil", "USA", "Mexique"]
                    #   0        1        2
continent_amerique[2]

'Mexique'

In [ ]:
# .info() permet de voir le nombre de lignes, colonnes, type de donnees etc..
#  et les valeurs nulles
product_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   product             10 non-null     object
 1   price               10 non-null     float64
 2   quantity            10 non-null     int64
 3   weight              10 non-null     float64
 4   height              10 non-null     float64
 5   location_available  10 non-null     object
dtypes: float64(3), int64(1), object(2)
memory usage: 612.0+ bytes

In [ ]:
# head(chiffre) permet de selectionner les premieres lignes X de la dataframe
product_df.head(3)

      product   price  quantity  weight  height location_available
0      Laptop  899.99        15    2.30     1.8           New York
1  Smartphone  699.50        40    0.18     0.7         California
2      Tablet  399.00        25    0.50     0.6              Texas

In [19]:
# meme chose que le head mais pour les dernieres lignes
product_df.tail(3)

   product   price  quantity  weight  height location_available
7    Mouse   39.99        70    0.12     0.9            Arizona
8  Printer  189.00        10    6.80    12.4            Georgia
9   Webcam   59.49        45    0.20     1.2             Oregon

In [55]:
sells_df = pd.read_csv("data/sells.csv")
sells_df

,id_client,product_information,quantity,amount,location,postal_code,age
0,ax01,Macbook_M1,150,15000,Paris,75000,45
1,ax02,samsung_watch_x1,1,1000,Paris,75000,25
2,ax03,Google_phone,2,2000,Paris,75000,35
3,ax03,Sony_m90,2,600,Paris,75000,35

In [27]:
product_df

            product   price  quantity  weight  height location_available
0        Macbook_M1  899.99        15    2.30     1.8           New York
1  samsung_watch_x1  699.50        40    0.18     0.7         California
2    Tablet_applexo  399.00        25    0.50     0.6              Texas
3          Sony_m90  129.99        60    0.25     0.3            Florida
4  samsung_watch_x1  249.75        30    0.09     0.4         Washington
5         Monitorx1  299.99        20    4.50    15.2           Illinois
6      Keyboardx901   79.95        50    0.80     1.5               Ohio
7          Mousex12   39.99        70    0.12     0.9            Arizona
8      Printeras10c  189.00        10    6.80    12.4            Georgia
9      Webcamasdasd   59.49        45    0.20     1.2             Oregon

In [ ]:
# creer une troisieme dataframe a partir des 2 existantes, 
# pour avoir une colonne total_weight et une colonne weight 
# # il faut que ca ait la meme structure que sells_df + les deux nouvelles colonnes



# --> je copie la table sells a laquelle je vais juste ajouter 2 nouvelles colonnes 
# sells_df + 2 nouvelles colonnes 
#     - une colonne qui existe deja dans table product
#     - une nouvelle colonne a devoir creer via calcul quantite * weight

In [57]:
# Left JOIN choisi pour repondre a cette requete 
# exemple de jointure 
# nouvelle_df = premiere_table.merge(deuxieme_table, on="colonne_commune", how="left")

# notre probleme est le suivant: les colonnes communes entre les deux tables sont product et product_information 
# !!! elles ne portent pas le meme nom dans les deux tables
# 2 solutions:
    # solution 1: renommer une des deux colonnes pour qu'elles aient le meme nom
    # solution 2: utiliser les parametres left_on et right_on dans la fonction merge
sells_enriched_df = sells_df.merge(
    product_df[["product", "weight"]],
    left_on = " product_information",
    right_on = "product",
    how = "left"
)

In [58]:
sells_enriched_df

,id_client,product_information,quantity,amount,location,postal_code,age,product,weight
0,ax01,Macbook_M1,150,15000,Paris,75000,45,Macbook_M1,2.30
1,ax02,samsung_watch_x1,1,1000,Paris,75000,25,samsung_watch_x1,0.18
2,ax02,samsung_watch_x1,1,1000,Paris,75000,25,samsung_watch_x1,0.09
3,ax03,Google_phone,2,2000,Paris,75000,35,NaN,NaN
4,ax03,Sony_m90,2,600,Paris,75000,35,Sony_m90,0.25

In [59]:
# creer ma nouvelle colonne: total_weight qui va etre egale a quantity * weight
sells_enriched_df["total_weight"] = sells_enriched_df[" quantity"] * sells_enriched_df["weight"]

sells_enriched_df

,id_client,product_information,quantity,amount,location,postal_code,age,product,weight,total_weight
0,ax01,Macbook_M1,150,15000,Paris,75000,45,Macbook_M1,2.30,345.00
1,ax02,samsung_watch_x1,1,1000,Paris,75000,25,samsung_watch_x1,0.18,0.18
2,ax02,samsung_watch_x1,1,1000,Paris,75000,25,samsung_watch_x1,0.09,0.09
3,ax03,Google_phone,2,2000,Paris,75000,35,NaN,NaN,NaN
4,ax03,Sony_m90,2,600,Paris,75000,35,Sony_m90,0.25,0.50